"""Train the multimodal architecture after a real feature table is supplied.
This script intentionally does not invent targets or structural labels.
"""
from pathlib import Path
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import roc_auc_score, average_precision_score, matthews_corrcoef

ROOT=Path(__file__).resolve().parents[1]
print('PROTAC-GEO training entry point')
print('Supply a validated feature table containing real chemical, sequence, geometry and outcome features.')
print('Recommended validation: scaffold split + leave-one-target-out + leave-one-E3-out + external validation.')
print('No synthetic/random embeddings are generated by this script.')
